
export const FORM_CONSTANTS = {
    NAME: "Name",
    ADD_HELPER: "Add a Helper",
    ADD_HELPER_NEARBY: "Add a Helper for",
    ENTER_FULL_NAME: "Enter your full name",
    ENTER_PHONE_NUMBER: "Enter your phone number",
    PROFILE_NAME: "Your Profile Name",
    REGISTER: "Register",
    REGISTER_BUSINESS: "Register Your Business",
    BUSINESS_NAME: "Business Name",
    SHORT_SUMMARY: "Short Summary",
    PHONE: "Phone",
    BUSINESS_ADDRESS: "Business Address",
    BUSINESS_PHOTO: "Business Photo",
    USE_CAMERA: "Use Camera",
    CATEGORY: "Category",
    WORKING_HOURS: "Working Hours",
    DESCRIPTION: "Description",
    DESCRIPTION_PLACEHOLDER: "Any additional information",
    WORKING_HOURS_PLACEHOLDER: "E.g. 9am-5pm Mon-Fri",
    CHOOSE_CATEGORY: "Choose a category",
    USE_GALLERY: "Use Gallery",
    COUNTRY: "Country",
    DEFAULT_COUNTRY: "India",
    CITY: "City",
    AREA: "Area",
    FLAT: "Flat / House No.",
    PIN_CODE: "Pin Code",
    SELECT_SOCIETY: "Select your Society",
    SOCIETY_NAME: "Society Name",
    VERIFY_ADDRESS: "Verify Address",
    UPDATE_ADDRESS: "Update Address",
    LOCATION_ERROR_MSG: "Could not fetch location. Please enter details manually.",
    SOCIETY_NOT_FOUND: "We dont serve in this location yet",
    TEXTAREA_HELP_TEXT: "After submitting, your society name will be updated, after admins approval."
};