
export const PRODUCTS_CONSTANTS = {
    BUSINESS: "Business",
    HOME: "Home",
    DIRECTORY: "Directory",
    PROFILE: "Profile",
    SEARCH_BUSINESS: "Search for businesses or services",
    NO_BUSINESS_FOUND: "No businesses found",
    SELECT_CATEGORY: "Select a category",
    ALL_BUSINESSES: "All Businesses",
    FEATURED_BUSINESSES: "Featured Businesses",
    POPULAR_CATEGORIES: "Popular Categories",
    POPULAR_BUSINESSES: "Popular Businesses",
    ACTIVE_WHOLESALE_DEALS: "Active Wholesale Deals",
    VIEW_ALL: "View All",
    VIEW_DEAL: "View Deals",
    VIEW_DEAL_: "View Deal",
    VIEW_PRODUCT: "View Product",
    ALL: "All",
    SERVICE: "Service",
    PRODUCT: "Product",
    CREATE_NEW_DEAL: "Create New Deal",
    WHOLESALE_DEAL_HOMEPAGE_SUMMARY: "Explore active deals from various wholesalers",
    WHOLESALE_DEAL_ID: "wholesale-deal-id",
    WHOLESALE_DEAL_WORK: "How Wholesale Deals Work",
    WHOLESALE_DEAL_WORK_DESC: "You set a minimum order goal. If enough neighbors join before the deadline, everyone gets the item at the wholesale price. If the goal is met, the deal is cancelled, and no one is charged.",
};